export const appInfos = {
  baseUrl: 'https://beta.eduop.in',
  localDataName: {
    accessToken: 'accessToken',
    userData: 'userData',
    scanlist: 'scanlist',
    shopingList: 'shopingList',
    groceryList: 'groceryList',
    dietType: 'dietType',
    favourites: 'favourites',
  },
  monthNames: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
};
